# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Trace_Matrix <- function(h, S) {
    .Call(`_stBase_Trace_Matrix`, h, S)
}

Trace_Muti <- function(S1, S2) {
    .Call(`_stBase_Trace_Muti`, S1, S2)
}

Solve <- function(A) {
    .Call(`_stBase_Solve`, A)
}

theta2_fun_C <- function(m_r, n_r, theta2_r, ds_r, D_r, bandKernel_r, Q_r, S00_r, S01_r, theta1_r, sigTheta1_r, nThreads_r) {
    .Call(`_stBase_theta2_fun_C`, m_r, n_r, theta2_r, ds_r, D_r, bandKernel_r, Q_r, S00_r, S01_r, theta1_r, sigTheta1_r, nThreads_r)
}

